apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: release-demo
  labels:
    app: release-demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: release-demo
  template:
    metadata:
      labels:
        app: release-demo
    spec:
      containers:
      - name: release-demo
        image: pjajodia/release-demo:3242fcd71044c84bc597dc03ad4e06fce6a48365
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 100