apiVersion: v1
kind: Service
metadata:
  name: release-demo-active
  namespace: qa
spec:
  selector:
    app: release-demo
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: release-demo-preview
  namespace: qa
spec:
  selector:
    app: release-demo
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP